#!/bin/bash
# Tweak the stock ubuntu cloud-init config

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# cloud-init May not actually be installed
mkdir -p /etc/cloud/cloud.cfg.d
# dd是对指定大小的块进行拷贝，并在拷贝的时候进行指定转换
if [ -n "${DIB_CLOUD_INIT_ETC_HOSTS:-}" ]; then
    dd of=/etc/cloud/cloud.cfg.d/10_etc_hosts.cfg << EOF
manage_etc_hosts: $DIB_CLOUD_INIT_ETC_HOSTS
EOF
fi
